mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.ulyer.baseclient.entity
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
