spring:
  activiti:
    check-process-definitions: false
    database-schema-update: true
    async-executor-activate: false
  liquibase:
    enabled: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  data:
    jpa:
      repositories:
        enabled: true
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
